# Default values for wpm aas manager.

nameOverride: "" # The name for AAS-MANAGER chart (Default: .Chart.Name)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying WPM chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas

image:
  svc:
    pullPolicy: Always # The pull policy for pulling from container registry for wpm aas manager <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication
    initName: <user input>
  aasManager:
    name: <user input> # The image registry where AAS Manager image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for AAS Manager<br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication

securityContext:
  aasManager: # The security content for AAS-MANAGER Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false
  aasManagerInit: # The fsGroup id for init containers for AAS DB
    fsGroup: 1001

aas:
  # Please update the url section if aas is exposed via ingress
  url:
  secret:
    adminUsername: # Admin Username for AAS
    adminPassword: # Admin Password for AAS

service:
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
  aas:
    containerPort: 8444 # The containerPort on which AAS can listen
    port: 30444 # The externally exposed NodePort on which AAS can listen to external traffic
