{{- include "factory.headers" . }}
---
{{- include "factory.serviceCommonSpec" . }}
  {{- if .Values.global }}
    {{- if .Values.global.ingress.enable }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.aas.containerPort }}
      targetPort: {{ .Values.service.aas.containerPort }}
    {{- else }}
  type: NodePort
  ports:
    - port: {{ .Values.service.aas.containerPort }}
      targetPort: {{ .Values.service.aas.containerPort }}
      nodePort: {{ .Values.global.service.aas }}
    {{- end }}
  {{- else if .Values.service.ingress.enable }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.aas.containerPort }}
      targetPort: {{ .Values.service.aas.containerPort }}
  {{- else }}
  type: NodePort
  ports:
    - port: {{ .Values.service.aas.containerPort }}
      targetPort: {{ .Values.service.aas.containerPort }}
      nodePort: {{ .Values.service.aas.port }}
  {{ end }}
