{{- include "factory.headers" . }}
---
{{- include "factory.deploymentCommonSpec" . }}
    spec:
      {{- if .Values.global }}
      {{- if .Values.global.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.imagePullSecret }}
      {{- end }}
      {{- else }}
      {{- if .Values.image.svc.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.svc.imagePullSecret }}
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext.hvsInit | nindent 8 }}
      serviceAccountName: {{ include "factory.name" . }}
      initContainers:
        {{- include "factory.initWaitForDb" . | nindent 8 }}
        {{- include "factory.initWaitForCmsSha384BearerToken" . | nindent 8 }}
        {{- include "factory.initCommonSpecLinkServiceVolumes" . | nindent 8 }}
          securityContext:
            {{- toYaml .Values.securityContext.hvs | nindent 12 }}
          volumeMounts:
            {{- include "factory.volumeMountsBasePv" . | nindent 12 }}
        {{- if .Values.global }}
        {{- if .Values.global.versionUpgrade }}
        {{- include "factory.waitForUpgradeService" . | nindent 8 }}
          securityContext:
            {{- toYaml .Values.securityContext.hvs | nindent 12 }}
        {{- end}}
        {{- else}}
        {{- if .Values.versionUpgrade }}
        {{- include "factory.waitForUpgradeService" . | nindent 8 }}
          securityContext:
            {{- toYaml .Values.securityContext.hvs | nindent 12 }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ include "factory.name" . }}
          {{- include "factory.imageContainer" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext.hvs | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "factory.name" . }}
          env:
            {{- include "factory.envCmsSha384" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.hvs.containerPort }}
          readinessProbe:
            httpGet:
              path: /hvs/v2/version
              port: {{ .Values.service.hvs.containerPort }}
              scheme: HTTPS
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 15
          volumeMounts:
          {{- include "factory.volumeMountSvcConfig" . | nindent 12 }}
          {{- include "factory.volumeMountSvcLogs" . | nindent 12 }}
          {{- include "factory.volumeMountsSvcDb" . | nindent 12 }}
      volumes:
        {{- include "factory.volumeSvcConfig" . | nindent 8 }}
        {{- include "factory.volumeSvcLogs" . | nindent 8 }}
        {{- include "factory.volumesSvcDb" . | nindent 8 }}
        {{- include "factory.volumesBasePV" . | nindent 8 }}
        {{- include "factory.volumeProjectedSecrets" . | nindent 8 }}
        {{- include "factory.volumeDbCredentials" . | nindent 12 }}
        {{- include "factory.volumeCredentials" . | nindent 12 }}
        {{- include "factory.volumeAasBearerToken" . | nindent 12 }}