{{- include "factory.headers" . }}
---
{{- include "factory.serviceCommonSpec" . }}
  {{- if .Values.global }}
  {{- if .Values.global.ingress.enable }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.hvs.containerPort }}
      targetPort: {{ .Values.service.hvs.containerPort }}
  {{- else }}
  type: NodePort
  ports:
    - port: {{ .Values.service.hvs.containerPort }}
      targetPort: {{ .Values.service.hvs.containerPort }}
      nodePort: {{ .Values.global.service.hvs }}
  {{- end }}
  {{- else if .Values.service.ingress.enable }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.hvs.containerPort }}
      targetPort: {{ .Values.service.hvs.containerPort }}
  {{- else }}
  type: NodePort
  ports:
    - port: {{ .Values.service.hvs.containerPort }}
      targetPort: {{ .Values.service.hvs.containerPort }}
      nodePort: {{ .Values.service.hvs.port }}
  {{- end }}